<?php
session_start();
session_register("isLogined_session");
session_register("pwd_session");

//Settings here:
$sqlite_file='./myfav.sdb3';

$FavPasswd="Fav_pass";
$ViewPassword="Fav+view";
$NewWin=true;
$shrinkFirst=true;

$TextboxWidth=50;

$homeTitle="My Web Faovrities";
$homeDesc="A simple Web Favorities System written in PHP.";
$itemDesc="A item generated by Web Favorities System.";
$authorName="Roy Tam";
// End of settings part

require_once('./fav_common.php'); // *** DETERMINATION SCRIPT, MODIFY WITH RISK! ***

// Auto Setup Part, no need to modify
$BaseURL=fullURL();
$homeURL=$BaseURL."fav.php";
$BackUrl=$homeURL;
$RSS_SELF=$BaseURL."rss.php";
$domainName=preg_replace('/\:.*/','',$_SERVER["HTTP_HOST"]); 

?>