//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GSPlayer2.rc
//
#define IDS_FILTER_OPEN_FILE            1
#define IDS_FILTER_OPEN_FILE2           2
#define IDS_TITLE_OPEN_FILE             3
#define IDS_TITLE_ADD_FILE              4
#define IDS_TITLE_FIND_FILE             5
#define IDS_TITLE_SAVE_LIST             6
#define IDS_FILTER_SAVE_LIST            7
#define IDS_TITLE_EQ                    8
#define IDS_TITLE_EFFECT                9
#define IDS_TITLE_BASSBOOST             10
#define IDS_MSG_ASSOCIATE               11
#define IDS_MSG_ASSOCIATE_DONE          12
#define IDS_TITLE_OPTION                13
#define IDS_FMT_DISP_INFO               14
#define IDS_FMT_DISP_VOLUME             15
#define IDS_TITLE_SKIN_FILE             16
#define IDS_FILTER_SKIN_FILE            17
#define IDS_TITLE_SAVE_EFFECT           18
#define IDS_MSG_CONNECTING              18
#define IDS_TITLE_LOAD_EFFECT           19
#define IDS_FMT_BUFFERING               19
#define IDS_FILTER_SAVE_EFFECT          20
#define IDS_FMT_BUFINFO                 20
#define IDS_FILTER_LOAD_EFFECT          21
#define IDS_FMT_DEL_PRESET              22
#define IDS_TITLE_DEL_PRESET            23
#define IDB_BACK                        101
#define IDI_MAIN                        101
#define IDR_POPUP                       101
#define IDM_SHOW_MENU                   101
#define IDD_ABOUT_DLG                   103
#define IDM_TOOL_VOLUP                  108
#define IDM_TOOL_VOLDOWN                109
#define IDD_PLAYLIST_DLG                111
#define IDI_FILE_S                      112
#define IDI_PLAY_S                      113
#define IDB_VOLSLIDER                   121
#define IDB_VOLTRACK                    122
#define IDD_LOCATION_DLG                128
#define IDB_NUMBER                      129
#define IDD_PAGE_EQUALIZER              130
#define IDB_STATUS                      130
#define IDB_BUTTON                      131
#define IDB_PLAYOPTION                  132
#define IDD_PAGE_PLAYER                 133
#define IDI_ROOT                        134
#define IDD_PAGE_EFFECT_SAVE            134
#define IDD_PAGE_PRESET                 134
#define IDD_PRESETNAME_DLG              135
#define IDB_BUTTONPUSH                  136
#define IDB_BUTTON_PUSH                 136
#define IDD_PAGE_REVERB                 136
#define IDB_BUTTON_NORMAL               137
#define IDD_SLEEPTIMER_DLG              137
#define IDD_PAGE_PLUGIN                 138
#define IDB_TRACK                       142
#define IDD_FOLDER_DLG                  146
#define IDD_PAGE_BASSBOOST              174
#define IDD_PAGE_EFFECT                 174
#define IDD_PAGE_STREAMING              175
#define IDD_PAGE_DECODER                176
#define IDD_PAGE_ASSOCIATE              177
#define IDD_PAGE_SKIN                   178
#define IDI_FILE                        200
#define IDI_PLAYLIST                    201
#define IDC_EDIT_BUFF                   1000
#define IDC_EDIT_PREBUFF                1001
#define IDC_PLAY_LIST                   1002
#define IDC_SPIN_BUFF                   1002
#define IDC_CHECK_SURROUND              1003
#define IDC_SPIN_PREBUFF                1003
#define IDC_UP                          1004
#define IDC_TREE_FOLDER                 1005
#define IDC_DOWN                        1005
#define IDC_SPIN_OUT_BUFF_COUNT         1005
#define IDC_SPIN_OUT_BUFF_LEN           1005
#define IDC_SPIN_OUT_PREBUFF            1006
#define IDC_DELETE                      1007
#define IDC_CHECK_MPG                   1008
#define IDC_CHECK_OGG                   1009
#define IDC_CHECK_WAV                   1010
#define IDC_CHECK_PLS                   1011
#define IDC_CMB_LOCATION                1012
#define IDC_CHECK1                      1012
#define IDC_CHECK_SUBFOLDER             1012
#define IDC_CHECK_AUTOPREAMP            1012
#define IDC_CHECK_TITLESCROLL           1012
#define IDC_CHECK_SCROLLTITLE           1012
#define IDC_CHECK_PROXY                 1012
#define IDC_CHECK_POWEROFF              1012
#define IDC_CHECK_3DCHORUS              1013
#define IDC_ADD                         1014
#define IDC_SAVE                        1015
#define IDC_EDIT_PROXY                  1016
#define IDC_LOAD                        1017
#define IDC_DEL                         1018
#define IDC_LIST_PRESET                 1019
#define IDC_EDIT_NAME                   1022
#define IDC_CHECK_8BITS_OUTPUT          1027
#define IDC_CHECK_HALFRATE              1028
#define IDC_TITLE                       1029
#define IDC_CHECK_OUTPUT_FADE           1029
#define IDC_CHECK_SCAN_COMPLETELY       1030
#define IDC_CHECK_SCANCOMPLETELY        1030
#define IDC_CHECK_BASSBOOST             1031
#define IDC_CHECK_ALWAYSOPENDEV         1031
#define IDC_CHECK_REVERB                1034
#define IDC_SLIDER_REVERB               1035
#define IDC_CHECK_RESUME                1036
#define IDC_CHECK_ECHO                  1036
#define IDC_SLIDER_EQ1                  1037
#define IDC_CHECK_PLAYONSTART           1037
#define IDC_SLIDER_EQ2                  1038
#define IDC_CHECK_TRAYICON              1038
#define IDC_SLIDER_ECHO                 1038
#define IDC_SLIDER_EQ3                  1039
#define IDC_SLIDER_EQ5                  1040
#define IDC_EDIT_FILE                   1040
#define IDC_BUTTON_FLAT                 1041
#define IDC_BROWSE                      1041
#define IDC_CHECK2                      1041
#define IDC_SLIDER_EQ4                  1042
#define IDC_CHECK_EQUALIZER             1043
#define IDC_SLIDER_PREAMP               1044
#define IDC_SLIDER_SURROUND             1045
#define IDC_SLIDER_3DCHORUS             1046
#define IDC_CHECK_TIMER                 1047
#define IDC_EDIT_OUT_BUFF_COUNT         1049
#define IDC_EDIT_OUT_BUFF_LEN           1049
#define IDC_EDIT_OUT_PREBUFF            1050
#define IDC_CHECK_PEEK                  1069
#define IDC_CHECK_SUPZERO               1069
#define IDC_CHECK_SAVE_DEFLIST          1070
#define IDC_CHECK_ADD_EXISTING          1071
#define IDC_SLIDER_BASSBOOST            1072
#define IDC_CHECK_SUPZERO2              1072
#define IDC_SLIDER_EQ6                  1076
#define IDC_EDIT_TIMER                  1076
#define IDC_SLIDER_EQ7                  1077
#define IDC_SLIDER_EQ8                  1078
#define IDC_SPIN_TIMER                  1078
#define IDC_SLIDER_EQ9                  1079
#define IDC_STATIC_BUFINFO              1079
#define IDC_SLIDER_EQ10                 1080
#define IDC_LIST_EXT                    1080
#define IDC_CHECK_ALL                   1081
#define IDC_CLEAR_ALL                   1082
#define IDC_CONFIG                      1083
#define IDC_LIST_PLUGIN                 1084
#define IDM_FILE_SAVE_LIST              40001
#define IDM_FILE_ADD                    40002
#define IDM_FILE_FIND                   40003
#define IDM_APP_EXIT                    40004
#define IDM_FILE_OPEN_LOCATION          40005
#define IDM_APP_SHOWHIDE                40006
#define IDM_HELP_ABOUT                  40008
#define IDM_TOOL_EFFECT                 40009
#define IDM_TOOL_OPTION                 40010
#define IDM_PLAY_REPEAT_NONE            40011
#define IDM_PLAY_REPEAT_ALL             40012
#define IDM_PLAY_REPEAT_ONE             40013
#define IDM_TOOL_SLEEPTIMER             40014
#define IDM_FILE_LIST                   40015
#define IDM_PLAY_REPEAT                 40016
#define IDM_PLAY_SHUFFLE                40017
#define IDM_FILE_OPEN                   40018
#define IDM_TOOL_TOPMOST                40020
#define IDM_PLAY_PLAYPAUSE              40027
#define IDM_PLAY_SELECTED               40028
#define IDM_FILE_UP                     40029
#define IDM_FILE_DOWN                   40030
#define IDM_FILE_DELETE                 40031
#define IDM_FILE_SORT_BYNAME            40032
#define IDM_FILE_SORT_BYPATH            40034
#define IDM_PLAY_STOP                   40036
#define IDM_PLAY_PREV                   40037
#define IDM_PLAY_NEXT                   40038
#define IDM_PLAY_REW                    40074
#define IDM_PLAY_FF                     40075
#define IDS_ROOT_FOLDER_NAME            40085
#define IDS_FILTER_OPEN_ALL             40086
#define IDS_FILTER_OPEN_SUPPORTED       40087
#define IDS_FILTER_OPEN_INTERNAL        40088
#define IDS_FMT_NULL_FILE_TYPE          40089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
