//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PokemonRomViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_PokemonRomVieweTYPE         129
#define IDI_DIALOG                      130
#define IDS_ERR_INIT                    150
#define IDS_ERR_ROM_READ                151
#define IDS_ERR_ROM_WRITE               152
#define IDS_WRN_ROM_READONLY            153
#define IDD_BEERY                       159
#define IDD_CONFIG                      170
#define IDD_WAIT                        171
#define IDD_BREED                       200
#define IDD_BREED_TYPE                  201
#define IDD_BREED_ABL                   202
#define IDD_BREED_SPEC                  203
#define IDD_BREED_ITEM                  204
#define IDD_BREED_LVLUP_LEARN           205
#define IDD_BREED_DERIVE_LEARN          206
#define IDD_BREED_MACHINE_LEARN         207
#define IDD_EVO                         220
#define IDD_ITEM                        230
#define IDD_SKILL                       240
#define IDD_ENC                         250
#define IDD_ROM_ENC_LAND                251
#define IDD_ROM_ENC_WATER               252
#define IDD_ROM_ENC_STONE               253
#define IDD_ROM_ENC_FISH                254
#define IDC_PM_LIST                     1000
#define IDC_REFRESH                     1001
#define IDC_CONFIRM                     1002
#define IDC_TAB                         1003
#define IDC_TYPE_LIST0                  1005
#define IDC_TYPE_LIST1                  1006
#define IDC_EG_LIST0                    1007
#define IDC_EG_LIST1                    1008
#define IDC_BRD_HP                      1010
#define IDC_BRD_ATK                     1011
#define IDC_BRD_DEF                     1012
#define IDC_BRD_DEX                     1013
#define IDC_BRD_SATK                    1014
#define IDC_BRD_SDEF                    1015
#define IDC_BRD_SUM                     1016
#define IDC_BB_HP                       1020
#define IDC_BB_ATK                      1021
#define IDC_BB_DEF                      1022
#define IDC_BB_DEX                      1023
#define IDC_BB_SATK                     1024
#define IDC_BB_SDEF                     1025
#define IDC_EVO_COND_LIST0              1030
#define IDC_EVO_COND_LIST1              1031
#define IDC_EVO_COND_LIST2              1032
#define IDC_EVO_COND_LIST3              1033
#define IDC_EVO_COND_LIST4              1034
#define IDC_EVO_COND_LIST5              1035
#define IDC_EVO_ICON0                   1040
#define IDC_EVO_ICON1                   1041
#define IDC_EVO_ICON2                   1042
#define IDC_EVO_ICON3                   1043
#define IDC_EVO_ICON4                   1044
#define IDC_EVO_ITEM_LIST0              1050
#define IDC_EVO_ITEM_LIST1              1051
#define IDC_EVO_ITEM_LIST2              1052
#define IDC_EVO_ITEM_LIST3              1053
#define IDC_EVO_ITEM_LIST4              1054
#define IDC_EVO_PARAM0                  1060
#define IDC_EVO_PARAM1                  1061
#define IDC_EVO_PARAM2                  1062
#define IDC_EVO_PARAM3                  1063
#define IDC_EVO_PARAM4                  1064
#define IDC_EVO_BRD_LIST0               1070
#define IDC_EVO_BRD_LIST1               1071
#define IDC_EVO_BRD_LIST2               1072
#define IDC_EVO_BRD_LIST3               1073
#define IDC_EVO_BRD_LIST4               1074
#define IDC_EVO_PARAM_DESC0             1080
#define IDC_EVO_PARAM_DESC1             1081
#define IDC_EVO_PARAM_DESC2             1082
#define IDC_EVO_PARAM_DESC3             1083
#define IDC_EVO_PARAM_DESC4             1084
#define IDC_UI_CN                       1090
#define IDC_UI_JP                       1091
#define IDC_UI_EN                       1092
#define IDC_COUNT_0                     1100
#define IDC_COUNT_10                    1101
#define IDC_COUNT_16                    1102
#define IDC_ROM_PATH                    1110
#define IDC_ROM_FILE_PATH               1110
#define IDC_BROWSE                      1111
#define IDC_BRD_CATCH_RATIO             1120
#define IDC_BRD_ESCAPE_RATIO            1121
#define IDC_BRD_FEMALE_RATIO            1122
#define IDC_BRD_HATCH_TIME              1123
#define IDC_BRD_INIT_INTIMATE           1124
#define IDC_BRD_BASE_EXP                1125
#define IDC_BRD_EXP_TYPE_LIST           1126
#define IDC_BRD_UNK                     1127
#define IDC_BRD_SPEC_LIST0              1130
#define IDC_BRD_SPEC_LIST1              1131
#define IDC_BRD_SPEC_DESC0              1135
#define IDC_BRD_SPEC_DESC1              1136
#define IDC_BRD_ITEM_LIST0              1140
#define IDC_BRD_ITEM_LIST1              1141
#define IDC_BRD_ITEM_DESC0              1145
#define IDC_BRD_ITEM_DESC1              1146
#define IDC_EVO_SET_BRD0                1153
#define IDC_EVO_SET_BRD1                1154
#define IDC_EVO_SET_BRD2                1155
#define IDC_EVO_SET_BRD3                1156
#define IDC_EVO_SET_BRD4                1157
#define IDC_ITM_ITEM_LIST               1160
#define IDC_ITM_PRICE                   1161
#define IDC_ITM_DESC                    1162
#define IDC_SKL_SKILL_LIST              1190
#define IDC_SKL_TYPE_LIST               1200
#define IDC_SKL_TARGET_LIST             1201
#define IDC_SKL_POWER                   1202
#define IDC_SKL_ACC                     1203
#define IDC_SKL_PP                      1204
#define IDC_SKL_EFFECT                  1205
#define IDC_SKL_EFFECT_RATIO            1206
#define IDC_SKL_PRIORITY                1207
#define IDC_SKL_DESC                    1208
#define IDC_SKL_MELEE                   1220
#define IDC_SKL_PROTECT                 1221
#define IDC_SKL_SUBSTITUTE              1222
#define IDC_SKL_UNK0                    1223
#define IDC_SKL_UNK1                    1224
#define IDC_SKL_KINGSROCK               1225
#define IDC_ENC_LIST                    1500
#define IDC_MIN_LEVEL0                  1510
#define IDC_MIN_LEVEL1                  1511
#define IDC_MIN_LEVEL2                  1512
#define IDC_MIN_LEVEL3                  1513
#define IDC_MIN_LEVEL4                  1514
#define IDC_MIN_LEVEL5                  1515
#define IDC_MIN_LEVEL6                  1516
#define IDC_MIN_LEVEL7                  1517
#define IDC_MIN_LEVEL8                  1518
#define IDC_MIN_LEVEL9                  1519
#define IDC_MIN_LEVEL10                 1520
#define IDC_MIN_LEVEL11                 1521
#define IDC_MAX_LEVEL0                  1530
#define IDC_MAX_LEVEL1                  1531
#define IDC_MAX_LEVEL2                  1532
#define IDC_MAX_LEVEL3                  1533
#define IDC_MAX_LEVEL4                  1534
#define IDC_MAX_LEVEL5                  1535
#define IDC_MAX_LEVEL6                  1536
#define IDC_MAX_LEVEL7                  1537
#define IDC_MAX_LEVEL8                  1538
#define IDC_MAX_LEVEL9                  1539
#define IDC_MAX_LEVEL10                 1540
#define IDC_MAX_LEVEL11                 1541
#define IDC_LAND_IMAGE0                 1550
#define IDC_LAND_IMAGE1                 1551
#define IDC_LAND_IMAGE2                 1552
#define IDC_LAND_IMAGE3                 1553
#define IDC_LAND_IMAGE4                 1554
#define IDC_LAND_IMAGE5                 1555
#define IDC_LAND_IMAGE6                 1556
#define IDC_LAND_IMAGE7                 1557
#define IDC_LAND_IMAGE8                 1558
#define IDC_LAND_IMAGE9                 1559
#define IDC_LAND_IMAGE10                1560
#define IDC_LAND_IMAGE11                1561
#define IDC_ENC_SET_BREED0              1570
#define IDC_ENC_SET_BREED1              1571
#define IDC_ENC_SET_BREED2              1572
#define IDC_ENC_SET_BREED3              1573
#define IDC_ENC_SET_BREED4              1574
#define IDC_ENC_SET_BREED5              1575
#define IDC_ENC_SET_BREED6              1576
#define IDC_ENC_SET_BREED7              1577
#define IDC_ENC_SET_BREED8              1578
#define IDC_ENC_SET_BREED9              1579
#define IDC_ENC_SET_BREED10             1580
#define IDC_ENC_SET_BREED11             1581
#define IDC_ENC_BREED_LIST0             1590
#define IDC_ENC_BREED_LIST1             1591
#define IDC_ENC_BREED_LIST2             1592
#define IDC_ENC_BREED_LIST3             1593
#define IDC_ENC_BREED_LIST4             1594
#define IDC_ENC_BREED_LIST5             1595
#define IDC_ENC_BREED_LIST6             1596
#define IDC_ENC_BREED_LIST7             1597
#define IDC_ENC_BREED_LIST8             1598
#define IDC_ENC_BREED_LIST9             1599
#define IDC_ENC_BREED_LIST10            1600
#define IDC_ENC_BREED_LIST11            1601
#define IDC_ENC_PARAM                   1610
#define IDC_ENC_FIND_EDIT               1800
#define IDC_ENC_FIND                    1801
#define IDC_BERRY_BERRY_LIST            1850
#define IDC_BERRY_FIRM                  1860
#define IDC_BERRY_SIZE                  1861
#define IDC_BERRY_MAX                   1862
#define IDC_BERRY_MIN                   1863
#define IDC_ORDER_INTERNAL              1863
#define IDC_BERRY_HOURS_PER_STAGE       1864
#define IDC_ORDER_KANTO                 1864
#define IDC_ORDER_HOUEN                 1865
#define IDC_BUTTON2                     1868
#define IDC_BERRY_SPICY                 1870
#define IDC_BERRY_DRY                   1871
#define IDC_BERRY_SWEET                 1872
#define IDC_BERRY_BITTER                1873
#define IDC_BERRY_SOUR                  1874
#define IDC_BERRY_FEEL                  1875
#define IDC_LUL_LIST                    1900
#define IDC_LUL_COUNT                   1901
#define IDC_LUL_SKILL_DESC              1902
#define IDC_LUL_SKILL                   1910
#define IDC_LUL_LEVEL                   1911
#define IDC_LUL_FROM_SKILL_DLG          1912
#define IDC_LUL_SET_SKILL               1913
#define IDC_DL_LIST                     1950
#define IDC_DL_COUNT                    1951
#define IDC_DL_SKILL_DESC               1952
#define IDC_DL_SET_SKILL                1960
#define IDC_DL_SKILL                    1961
#define IDC_DL_FROM_SKILL_DLG           1962
#define IDC_ML_LIST                     2000
#define IDC_ML_COUNT                    2001
#define IDC_ML_SKILL_DESC               2002
#define IDC_ML_CHECK_ALL                2010
#define IDC_ML_CHECK_SEL                2011
#define IDC_ML_UNCHECK_ALL              2012
#define IDC_ML_UNCHECK_SEL              2013
#define IDC_ML_ORDER_MACHINE            2020
#define IDC_ML_ORDER_CHECKED            2021
#define IDC_FROM_EVO                    3010
#define IDC_FROM_BRD                    3020
#define IDC_REVERSE_FIND                3021
#define IDC_SHOW_EXPORT_BUTTONS         3030
#define IDC_EXPORT_BRD                  3031
#define IDC_EXPORT_EVO                  3032
#define IDC_EXPORT_LEARN                3033
#define IDC_EXPORT_MACHINE              3034
#define IDC_EXPORT_SKILL                3035
#define IDC_EXPORT_INDEX                3036
#define IDC_PROGRESS                    4000
#define IDC_DESC                        4001
#define ID_CONFIG                       32775
#define ID_SHOW_BREED                   32776
#define ID_SHOW_EVO                     32777
#define ID_SHOW_ITEM                    32778
#define ID_SHOW_SKILL                   32779
#define ID_SHOW_ENC                     32780
#define ID_SHOW_BERRY                   32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1869
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
