/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-i386"
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define TARGET_PHYS_ADDR_BITS 32
#define CONFIG_SOFTMMU 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
