# Automatically generated by configure - do not modify
SRC_PATH=/home/roy/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/usr/home/User/qemu-pc98_20091005-p2/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
