//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GSPlayer2.rc
//
#define IDS_FILTER_OPEN_FILE            1
#define IDS_TITLE_OPEN_FILE             2
#define IDS_TITLE_ADD_FILE              3
#define IDS_TITLE_FIND_FILE             4
#define IDS_TITLE_SAVE_LIST             5
#define IDS_FILTER_SAVE_LIST            6
#define IDS_TITLE_EQ                    7
#define IDS_TITLE_EFFECT                8
#define IDS_TITLE_BASSBOOST             9
#define IDS_MSG_ASSOCIATE               10
#define IDS_MSG_ASSOCIATE_DONE          11
#define IDS_TITLE_OPTION                12
#define IDS_FMT_DISP_INFO               13
#define IDS_FMT_DISP_VOLUME             14
#define IDS_TITLE_SKIN_FILE             15
#define IDS_FILTER_SKIN_FILE            16
#define IDS_TITLE_SAVE_EFFECT           17
#define IDS_MSG_CONNECTING              17
#define IDS_TITLE_LOAD_EFFECT           18
#define IDS_FMT_BUFFERING               18
#define IDS_FILTER_SAVE_EFFECT          19
#define IDS_FMT_BUFINFO                 19
#define IDS_FILTER_LOAD_EFFECT          20
#define IDS_FILTER_OPEN_ALL             20
#define IDS_FILTER_OPEN_SUPPORTED       21
#define IDS_FILTER_OPEN_INTERNAL        22
#define IDS_FMT_NULL_FILE_TYPE          23
#define IDS_FMT_DEL_PRESET              24
#define IDS_TITLE_DEL_PRESET            25
#define IDI_MAIN                        101
#define IDB_BACK                        101
#define IDR_POPUP                       101
#define IDD_PAGE_ASSOCIATE              102
#define IDD_ABOUT_DLG                   103
#define IDM_TOOL_VOLUP                  108
#define IDM_TOOL_VOLDOWN                109
#define IDM_SHOW_MENU                   110
#define IDD_PLAYLIST_DLG                111
#define IDI_FILE_S                      114
#define IDI_PLAY_S                      115
#define IDB_VOLSLIDER                   121
#define IDB_VOLTRACK                    122
#define IDD_LOCATION_DLG                130
#define IDD_PAGE_EQUALIZER              131
#define IDD_PAGE_PLAYER                 132
#define IDB_TRACK                       133
#define IDB_NUMBER                      136
#define IDB_STATUS                      137
#define IDB_BUTTON                      138
#define IDB_PLAYOPTION                  139
#define IDD_PAGE_EFFECT_SAVE            140
#define IDD_PAGE_PRESET                 140
#define IDD_PRESETNAME_DLG              141
#define IDB_BUTTONPUSH                  142
#define IDB_BUTTON_PUSH                 142
#define IDD_PAGE_REVERB                 142
#define IDB_BUTTONNORMAL                143
#define IDB_BUTTON_NORMAL               143
#define IDD_DIALOG1                     143
#define IDD_SLEEPTIMER_DLG              145
#define IDD_PAGE_PLUGIN                 146
#define IDD_PAGE_BASSBOOST              174
#define IDD_PAGE_EFFECT                 174
#define IDD_PAGE_STREAMING              175
#define IDD_PAGE_DECODER                176
#define IDD_PAGE_WNDALPHA               177
#define IDD_PAGE_SKIN                   178
#define IDI_FILE                        200
#define IDI_PLAYLIST                    201
#define IDC_PLAY_LIST                   1002
#define IDC_CHECK_SURROUND              1003
#define IDC_UP                          1004
#define IDC_DOWN                        1005
#define IDC_DELETE                      1007
#define IDC_ADD                         1008
#define IDC_CMB_LOCATION                1012
#define IDC_EDIT_PROXY                  1016
#define IDC_EDIT_BUFF                   1020
#define IDC_EDIT_PREBUFF                1021
#define IDC_SPIN_BUFF                   1023
#define IDC_SPIN_PREBUFF                1024
#define IDC_SPIN_OUT_BUFF_COUNT         1026
#define IDC_SPIN_OUT_BUFF_LEN           1026
#define IDC_CHECK_8BITS_OUTPUT          1027
#define IDC_SPIN_OUT_PREBUFF            1027
#define IDC_CHECK_HALFRATE              1028
#define IDC_CHECK_OUTPUT_FADE           1029
#define IDC_CHECK_RESUME                1036
#define IDC_SLIDER_EQ1                  1037
#define IDC_CHECK_PLAYONSTART           1037
#define IDC_SLIDER_EQ2                  1038
#define IDC_SLIDER_EQ3                  1039
#define IDC_SLIDER_ALPHA                1039
#define IDC_SLIDER_EQ5                  1040
#define IDC_EDIT_FILE                   1040
#define IDC_BUTTON_FLAT                 1041
#define IDC_BROWSE                      1041
#define IDC_SLIDER_EQ4                  1042
#define IDC_CHECK_TRAYICON              1042
#define IDC_CHECK_EQUALIZER             1043
#define IDC_CHECK_MPG                   1043
#define IDC_SLIDER_PREAMP               1044
#define IDC_CHECK_OGG                   1044
#define IDC_SLIDER_SURROUND             1045
#define IDC_CHECK_WAV                   1045
#define IDC_CHECK_PLS                   1046
#define IDC_SLIDER_3DCHORUS             1046
#define IDC_CHECK1                      1047
#define IDC_CHECK_SCANCOMPLETELY        1047
#define IDC_CHECK_AUTOPREAMP            1047
#define IDC_CHECK_TITLESCROLL           1047
#define IDC_CHECK_SCROLLTITLE           1047
#define IDC_CHECK_PROXY                 1047
#define IDC_CHECK_TIMER                 1047
#define IDC_CHECK_3DCHORUS              1048
#define IDC_EDIT_OUT_BUFF_COUNT         1049
#define IDC_SAVE                        1049
#define IDC_EDIT_OUT_BUFF_LEN           1049
#define IDC_EDIT_OUT_PREBUFF            1050
#define IDC_LOAD                        1051
#define IDC_DEL                         1055
#define IDC_LIST_PRESET                 1056
#define IDC_EDIT_NAME                   1057
#define IDC_CHECK_BASSBOOST             1062
#define IDC_CHECK_PEEK                  1069
#define IDC_CHECK_SUPZERO               1069
#define IDC_CHECK_SAVE_DEFLIST          1070
#define IDC_CHECK_REVERB                1070
#define IDC_CHECK_ADD_EXISTING          1071
#define IDC_SLIDER_REVERB               1071
#define IDC_SLIDER_BASSBOOST            1072
#define IDC_CHECK_ECHO                  1072
#define IDC_SLIDER_ECHO                 1073
#define IDC_CHECK_ALWAYSOPENDEV         1074
#define IDC_SLIDER_EQ6                  1076
#define IDC_EDIT_TIMER                  1076
#define IDC_SLIDER_EQ7                  1077
#define IDC_SLIDER_EQ8                  1078
#define IDC_SPIN_TIMER                  1078
#define IDC_SLIDER_EQ9                  1079
#define IDC_STATIC_BUFINFO              1079
#define IDC_SLIDER_EQ10                 1080
#define IDC_LIST_EXT                    1080
#define IDC_CHECK_ALL                   1081
#define IDC_CLEAR_ALL                   1082
#define IDC_CONFIG                      1083
#define IDC_LIST_PLUGIN                 1084
#define IDM_FILE_ADD                    40002
#define IDM_FILE_FIND                   40003
#define IDM_APP_EXIT                    40004
#define IDM_HELP_ABOUT                  40008
#define IDM_TOOL_EFFECT                 40009
#define IDM_TOOL_OPTION                 40010
#define IDM_FILE_LIST                   40015
#define IDM_PLAY_REPEAT                 40016
#define IDM_PLAY_SHUFFLE                40017
#define IDM_FILE_OPEN                   40018
#define IDM_TOOL_TOPMOST                40020
#define IDM_FILE_SAVE_LIST              40021
#define IDM_FILE_OPEN_LOCATION          40022
#define IDM_APP_SHOWHIDE                40023
#define IDM_PLAY_REPEAT_NONE            40024
#define IDM_PLAY_REPEAT_ALL             40025
#define IDM_PLAY_REPEAT_ONE             40026
#define IDM_PLAY_PLAYPAUSE              40027
#define IDM_PLAY_SELECTED               40028
#define IDM_FILE_UP                     40029
#define IDM_FILE_DOWN                   40030
#define IDM_FILE_DELETE                 40031
#define IDM_FILE_SORT_BYNAME            40032
#define IDM_TOOL_SLEEPTIMER             40033
#define IDM_FILE_SORT_BYPATH            40034
#define IDM_FILE_SORT_BYTRACKNUM        40035
#define IDM_PLAY_STOP                   40036
#define IDM_PLAY_PREV                   40037
#define IDM_PLAY_NEXT                   40038
#define IDM_FILE_SORT_BYARTIST          40039
#define IDM_FILE_SORT_BYTRACKNAME       40040
#define IDM_PLAY_REW                    40074
#define IDM_PLAY_FF                     40075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40041
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
