<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/2002/REC-xhtml1-20020801/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-tw" lang="zh-tw">
<head>
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
<link rel="alternate" type="application/xml" title="RSS 2.0 Feed" href="rss.php" />
<title>Firefox Musume Release builds</title>
<style type="text/css">
html {
  color: #ceeaf9;
  background: #008ad0 url("../bg.png") repeat-x;
  font-family:sans-serif;
}
kbd,samp {font-family:sans-serif;}
div samp {position:absolute; left:40%;}
div kbd {position:absolute; right:0.5em;}
.bold {font-weight:bold;}
</style>
<!--[if IE]>
<style type="text/css">
html {
  background: #0080CB url("../bg.png") repeat-x;
}
</style>
<![endif]-->
<script type="text/javascript">
function hoverThis(obj) {obj.style.background="#0077CC";}
function unhoverThis(obj) {obj.style.background="transparent";}
</script>
</head>
<body>
<h2>Firefox Musume Release Builds</h2>
<p>
<?php if(file_exists('./welcome.msg')) include('./welcome.msg'); ?>
</p>
Downloads:
<div style='border-bottom:1px solid'><span class="bold">Item</span> <samp><span class="bold">Size</span></samp> <kbd><span class="bold">Date</span></kbd></div>
