#Joyful Note Strings
$jnstr_colon='：';
$jnstr_addrblock = "アクセスを許可されていません";
$jnstr_NGWord="NGワードが含まれているので送信できません";
$jnstr_backtotop = "トップに戻る";
$jnstr_howto = "留意事項";
$jnstr_find = "ワード検索";
$jnstr_pastlog = "過去ログ";
$jnstr_admin = "管理用";
$jnstr_reload = "リロード";
$jnstr_poster = "投稿者";
$jnstr_postdate = "投稿日";
$jnstr_reslink = "[返信]";
$jnstr_gotores = "フォームへ移動";
$jnstr_prevpage_pre = "前の";
$jnstr_post_n = "件";
$jnstr_nextpage_pre = "次の";
$jnstr_form_pre = "以下のフォームから自分の投稿記事を修正・削除することができます";
$jnstr_proc = "処理";
$jnstr_proclink = "[処理]";
$jnstr_usr_edt = "修正";
$jnstr_usr_del = "削除";
$jnstr_usr_del_img = "添付ファイルを削除";
$jnstr_resno = "記事No";
$jnstr_delkey = "暗証キー";
$jnstr_submit = "送信";
$jnstr_contpost = "連続投稿はもうしばらく時間をおいて下さい";
$jnstr_wrongreq = "不正な返信要求です";
$jnstr_wrongpost = "不正な投稿です";
$jnstr_posted = "投稿は正常に処理されました。";
$jnstr_redirect = "ジャンプを待ってください。";
$jnstr_backtobbs = "掲示板へ戻る";
$jnstr_cannotupload = "アップロードできません";
$jnstr_uploadfail = "アップロード失敗";
$jnstr_back = "戻る";
$jnstr_notitle = "無題";
$jnstr_allthread="スレッド一覧はこちら";
$jnstr_overflow_pre="※レス";
$jnstr_overflow_post="件省略 全て読むには返信ボタンを押してください";
$jnstr_size_warn="この添付ファイルは容量リミットの原因なので、もうすぐ消えます。";
$jnstr_find_pre = "<li>検索したい<b>キーワード</b>を入力し、「条件」「表示」を選択して検索ボタンを押して下さい。</li><li>キーワードは「半角スペース」で区切って複数指定することができます。</li>";
$jnstr_find_keyword = "キーワード".$jnstr_colon;
$jnstr_cond = "条件".$jnstr_colon;
$jnstr_display = "表示".$jnstr_colon;
$jnstr_search = "検索";
$jnstr_search_result = "検索結果".$jnstr_colon;
$jnstr_search_again = "検索やり直し";
$jnstr_resfor = "へのレス";
$jnstr_admin_remake = "TOPページを更新する";
$jnstr_admin_cap = "キャップ事務所";
$jnstr_admin_pre = "パスワードを入力して下さい";
$jnstr_verify = "認証";
$jnstr_wrongpass = "パスワードが違います";
$jnstr_adminmode = "管理モード";
$jnstr_adminpage_pre = "<li>記事を削除する場合は「削除」のチェックボックスにチェックを入れ「送信する」を押して下さい。</li><li>画像許可を行なう場合は「画像許可」のチェックボックスにチェックを入れ「送信する」を押して下さい。</li>";
$jnstr_reset = "リセット";
$jnstr_commets = "コメント";
$jnstr_hostname = "ホスト名";
$jnstr_img = "画像";
$jnstr_allowimg = "画像<br>許可";
$jnstr_attachfile_total_pre = "【添付データ総数".$jnstr_colon;
$jnstr_attachfile_total_post = "KB】";
$jnstr_user_mod_err = "記事Noまたはパスワードが入力モレです";
$jnstr_user_mod_nopass = "該当記事にはパスワードが設定されていません";
$jnstr_user_mod_wrongpass = "パスワードが違います";
$jnstr_user_del_img = "添付ファイルを削除しました。";
$jnstr_user_del = "記事を削除しました。";
$jnstr_postnotfound = "該当記事が見当たりません";
$jnstr_user_edted_pre = "以下のとおり修正が完了しました";
$jnstr_wrongaddr = "不正なアクセスです";
$jnstr_namemissed = "名前が入力されていません";
$jnstr_img_pre = "添付ファイル：";
$jnstr_img_sample = "[サムネイル]";
$jnstr_noname = "名無し";
$jnstr_commentsmissed = "コメントが入力されていません";
$jnstr_nocomments = "本文なし";
$jnstr_emailmissed = "Ｅメールが入力されていません";
$jnstr_wrongemail = "Ｅメールの入力内容が不正です";
$jnstr_sendmailfail="送信失敗";
$jnstr_invalidcap="無効のキャップ";
$jnstr_name = "名前";
$jnstr_email = "e-Mail";
$jnstr_title = "題名";
$jnstr_user_edt_pre = "変更する部分のみ修正して送信ボタンを押して下さい";
$jnstr_attachment = "添付File";
$jnstr_delkey_post = "(英数字で8文字以内)";
$jnstr_txtcol = "文字色";
$jnstr_chkimg = "<li>画像は管理者が許可するまで「COMING SOON」のアイコンが表示されます。</li>";
$jnstr_howto_email1 = "記事を投稿する上での必須入力項目は<b>「おなまえ」「Ｅメール」「メッセージ」</b>です。ＵＲＬ、題名、削除キーは任意です。";
$jnstr_howto_email2 = "記事を投稿する上での必須入力項目は<b>「おなまえ」</b>と<b>「メッセージ」</b>です。Ｅメール、ＵＲＬ、題名、削除キーは任意です。";
$jnstr_howto_title = "掲示板の利用上の注意";
$jnstr_howto_cookie = "この掲示板は<b>クッキー対応</b>です。１度記事を投稿いただくと、おなまえ、Ｅメール、ＵＲＬ、削除キーの情報は２回目以降は自動入力されます。（ただし利用者のブラウザがクッキー対応の場合）";
$jnstr_howto_upload_pre = "画像などのバイナリーファイルをアップロードすることが可能です。";
$jnstr_howto_upload_type = "添付可能ファイル".$jnstr_colon;
$jnstr_howto_upload_maxsize = "最大投稿データ量".$jnstr_colon;
$jnstr_howto_upload_img_pre = "画像は横";
$jnstr_howto_upload_img_mid = "ピクセル、縦";
$jnstr_howto_upload_img_post = "ピクセルを超えると縮小表示されます。";
$jnstr_howto_notag = "投稿内容には、<b>タグは一切使用できません。</b>";
$jnstr_howto_otherrules = "<li><s>記事には、<b>半角カナは一切使用しないで下さい。</b>文字化けの原因となります。</s></li><li>記事の投稿時に<b>「削除キー」</b>にパスワード（英数字で8文字以内）を入れておくと、その記事は次回<b>削除キー</b>によって削除することができます。</li><li>既存の記事に<b>「返信」</b>をすることができます。各記事の上部にある<b>「返信」</b>ボタンを押すと返信用フォームが現れます。</li><li>管理者が著しく不利益と判断する記事や他人を誹謗中傷する記事は予告なく削除することがあります。";
$jnstr_howto_logmax_pre = "記事の保持件数は<b>最大 ";
$jnstr_howto_logmax_post = $jnstr_post_n."</b>です。それを超えると古い順に自動削除されます。";
$jnstr_howto_pastlog_pre = "過去の投稿記事から<b>「キーワード」によって簡易検索ができます。</b>トップメニューの<a href='";
$jnstr_howto_pastlog_post = "'>「ワード検索」</a>のリンクをクリックすると検索モードとなります。";
$jnstr_pastlog='過去ログ';
$jnstr_move='移動';
$jnstr_check_arrow='→';
$jnstr_check_log='ログ';
$jnstr_check_file='ファイル';
$jnstr_check_path='のパス';
$jnstr_check_permission='のパーミッション';
$jnstr_check_counter='カウンタ';
$jnstr_check_setted='設定あり';
$jnstr_check_notset='設定なし';
$jnstr_check_lock='ロック';
$jnstr_check_mode='形式';
$jnstr_check_dir='ディレクトリ';
$jnstr_check_img='画像';
$jnstr_sampleresize='サムネイルライブラリ';
$jnstr_have='有';
$jnstr_nothave='無';
$jnstr_chibi_gotobbs="掲示板へリンク";
$jnstr_chibi_showpost_pre="掲示板の先頭";
$jnstr_chibi_showpost_post=$jnstr_post_n."の記事が順番に表示されます。";

$jnstr_chibi_rights_1=<<"EOM";
    <a href="http://www.kent-web.com/" target="_blank">KENT</a> &amp; <a href="http://village.infoweb.ne.jp/~fwhf2602/" target="_blank">MakiMaki</a>
    <p style="color: #585eaa;"><strong>KENT</strong>さんの掲示板「<strong>YY-BOARD</strong>」を ・・・・・</p>
EOM

$jnstr_chibi_rights_2=<<"EOM";
    <a href="http://homepage2.nifty.com/nejifactory/" target="_blank">NejiFactory</a>
    <p style="color: #005344;"><strong>NejiFactory</strong>さんの「<strong>ちびぼーど</strong>」風に表示する為の ・・・・・</p>
EOM

$jnstr_chibi_rights_3=<<"EOM";
    コード参考<a href="http://yurii.oheya.to/" target="_blank">*繊細友の会ｌａｂ*</a>
    <p style="color: #aa363d;">閲覧専用のＣＧＩなのです！！ ＼(-o-;)／</p>
EOM

$jnstr_chibi_notice=<<"EOM";
    注意 )
    <p style="color: #472d56;">当CGIは閲覧以外の機能は「Joyful Note」に依存します。</p>
EOM

$jnstr_modcap_publish='キャップ発行';
$jnstr_modcap_del='キャップ抹消';
$jnstr_modcap_showall='キャップ一覧';
$jnstr_modcap_stop_hint='(停止＝抹消したいキャップを選択して停止を押してください。)';
$jnstr_modcap_stop='キャップ停止';
$jnstr_modcap_nocap='そんなキャップありませんでしたよ！';
$jnstr_modcap_ereased_title='キャップ抹消しました';
$jnstr_modcap_ereased_header='キャップの抹消成功';
$jnstr_modcap_ereased_body='抹消しました。';
$jnstr_modcap_erease_title='キャップ抹消フォーム';
$jnstr_modcap_erease_hint='[発行停止するキャップの投稿で表示される名前]';
$jnstr_modcap_publish_ngchar='名前に使えない文字が含まれています。';
$jnstr_modcap_publish_starchar='名前に★は使えません。';
$jnstr_modcap_publish_longname='名前が長いですよ。';
$jnstr_modcap_publish_longpass='キャップパスが長いですよ。';
$jnstr_modcap_publish_samecap='すでに同じキャップの人がいました。';
$jnstr_modcap_publish_finish_title='キャップ発行成功';
$jnstr_modcap_publish_finish_header='キャップの発行成功！';
$jnstr_modcap_publish_finish_body='キャップの発行が終わりました。';
$jnstr_modcap_namecolor='名前の色';
$jnstr_modcap_capsuffix='キャップ接尾語';
$jnstr_modcap_publish_form='キャップ発行フォーム';
$jnstr_modcap_publish_cappass='キャップパス';
$jnstr_modcap_publish_hint='(最後の★は入力しないでください。投稿時に自動で表示されます。)';
$jnstr_res_mode='レスモード';
$jnstr_edit_mode='修正モード';
