#Joyful Note Strings
$jnstr_colon='：';
$jnstr_addrblock = "您所使用的連線已被拒絕";
$jnstr_NGWord="您所發出的投稿含有禁語，投稿已被拒絕";
$jnstr_backtotop = "回首頁";
$jnstr_howto = "留意事項";
$jnstr_find = "關鍵字搜尋";
$jnstr_pastlog = "過去記錄";
$jnstr_admin = "管理用";
$jnstr_reload = "重新整理";
$jnstr_poster = "投稿者";
$jnstr_postdate = "投稿日";
$jnstr_reslink = "[回覆]";
$jnstr_gotores = "移動至表單";
$jnstr_prevpage_pre = "前";
$jnstr_post_n = "件";
$jnstr_nextpage_pre = "後";
$jnstr_form_pre = "以下的表單是用於修正・刪除自己的留言或貼圖";
$jnstr_proc = "處理項目";
$jnstr_proclink = "[處理]";
$jnstr_usr_edt = "修正";
$jnstr_usr_del = "刪除";
$jnstr_usr_del_img = "附件刪除";
$jnstr_resno = "投稿編號";
$jnstr_delkey = "密碼";
$jnstr_submit = "送出";
$jnstr_contpost = "連續投稿請稍候一段時間";
$jnstr_wrongreq = "不正確的回覆請求";
$jnstr_wrongpost = "不正確的投稿";
$jnstr_posted = "投稿已經正常處理，";
$jnstr_redirect = "請等待跳轉。";
$jnstr_backtobbs = "回到版面";
$jnstr_cannotupload = "不能上傳";
$jnstr_uploadfail = "上傳失敗";
$jnstr_back = "返回";
$jnstr_notitle = "無題";
$jnstr_allthread="按此檢視主題列表";
$jnstr_overflow_pre="※有";
$jnstr_overflow_post="件回覆被省略。要閱讀所有回應請按下回應連結。";
$jnstr_size_warn="這篇因附加檔案容量限制，附加檔案不久後就會刪除。";
$jnstr_find_pre = "<li>填入想搜尋的<b>關鍵字</b>、調整「條件」與「一次顯示數量」後請按下[搜索]按鈕。</li><li>關鍵字可使用「半形空白」來區別、進行複數條件的搜尋。</li>";
$jnstr_find_keyword = "關鍵字".$jnstr_colon;
$jnstr_cond = "條件".$jnstr_colon;
$jnstr_display = "一次顯示數量".$jnstr_colon;
$jnstr_search = "搜索";
$jnstr_search_result = "搜索結果".$jnstr_colon;
$jnstr_search_again = "再次搜索";
$jnstr_resfor = "的回覆";
$jnstr_admin_remake = "更新版面";
$jnstr_admin_cap = "Cap事務所";
$jnstr_admin_pre = "請輸入密碼";
$jnstr_verify = "認証";
$jnstr_wrongpass = "密碼錯誤";
$jnstr_adminmode = "管理模式";
$jnstr_adminpage_pre = "<li>刪除記事只需要在「刪除」一欄勾上並按[送出]按鈕即可。</li><li>畫像許可只需要在「畫像許可」一欄勾上並按[送出]按鈕即可。</li>";
$jnstr_reset = "重置";
$jnstr_commets = "內容";
$jnstr_hostname = "主機名稱";
$jnstr_img = "附件";
$jnstr_allowimg = "畫像<br>許可";
$jnstr_attachfile_total_pre = "【附件總大小".$jnstr_colon;
$jnstr_attachfile_total_post = "KB】";
$jnstr_user_mod_err = "投稿編號與密碼皆不能為空";
$jnstr_user_mod_nopass = "這個記事的密碼沒有設置";
$jnstr_user_mod_wrongpass = $jnstr_wrongpass;
$jnstr_user_del_img = "附件已刪除。";
$jnstr_user_del = "投稿已刪除。";
$jnstr_postnotfound = "找不到記事";
$jnstr_user_edted_pre = "以下資料已經修正";
$jnstr_wrongaddr = "不正確的網址";
$jnstr_namemissed = "沒有輸入名稱";
$jnstr_img_pre = "附件".$jnstr_colon;
$jnstr_img_sample = "[以預覽圖顯示]";
$jnstr_noname = "無名氏";
$jnstr_commentsmissed = "沒有輸入內容";
$jnstr_nocomments = "無內容";
$jnstr_emailmissed = "沒有輸入e-Mail";
$jnstr_wrongemail = "輸入的e-Mail内容不正確";
$jnstr_sendmailfail="送信失敗";
$jnstr_invalidcap="無效的Cap";
$jnstr_name = "名稱";
$jnstr_email = "e-Mail";
$jnstr_title = "標題";
$jnstr_user_edt_pre = "請更改需要的部份然後按[送出]按鈕";
$jnstr_attachment = "附件";
$jnstr_delkey_post = "(英數字8字元以内)";
$jnstr_txtcol = "文字色";
$jnstr_chkimg = "<li>畫像未得到管理人許可前會以「COMING SOON」顯示。</li>";
$jnstr_howto_email1 = "投稿時請務必輸入<b>「$jnstr_name」「$jnstr_email」「$jnstr_commets」</b>。ＵＲＬ、$jnstr_title、$jnstr_delkey可以空白不填。";
$jnstr_howto_email2 = "投稿時請務必輸入<b>「$jnstr_name」</b>和<b>「$jnstr_commets」</b>。$jnstr_email、ＵＲＬ、$jnstr_title、$jnstr_delkey可以空白不填。";
$jnstr_howto_title = "掲示板使用注意事項";
$jnstr_howto_cookie = "這個BBS有使用Cookie。第1次投稿之後、ID、E-mail、URL、刪除密碼會自動在第2次投稿時自動填入。（只對應於瀏覽器支援的場合）";
$jnstr_howto_upload_pre = "這裡可以上傳圖像檔案。";
$jnstr_howto_upload_type = "可以附加的檔案種類".$jnstr_colon;
$jnstr_howto_upload_maxsize = "最大檔案大小".$jnstr_colon;
$jnstr_howto_upload_img_pre = "當圖片的大小超過横";
$jnstr_howto_upload_img_mid = "像素、縦";
$jnstr_howto_upload_img_post = "像素會以縮圖顯示。";
$jnstr_howto_notag = "請勿於投稿内容使用任何html標籤。";
$jnstr_howto_otherrules = "<li><s>請勿使用半形仮名、這樣會造成顯示混亂。</s></li><li>投稿時可填入8位英數字母的<b>「$jnstr_delkey」</b>可用於之後萬一想要刪除自己留言或是貼圖的場合。</li><li>按下毎串右方的<b> $jnstr_reslink </b>可進行回文。會出現回覆表格提供填寫。</li><li>管理者有權擅自刪除任何含有不符合本板主旨與損害善良道德的内容的投稿。";
$jnstr_howto_logmax_pre = "本板可保存 <b>最多";
$jnstr_howto_logmax_post = "$jnstr_post_n</b>投稿。超過這個數字就會從最舊的投稿開始自動刪除。";
$jnstr_howto_pastlog_pre = "舊的投稿記事可使用<b>「關鍵字」</b>進行搜尋。點選主畫面上方的<a href='";
$jnstr_howto_pastlog_post = "'>「關鍵字搜尋」</a>可進入搜尋模式。";
$jnstr_pastlog='過去紀錄';
$jnstr_move='移動';
$jnstr_check_arrow='→';
$jnstr_check_log='紀錄';
$jnstr_check_file='檔案';
$jnstr_check_path='路徑';
$jnstr_check_permission='權限';
$jnstr_check_counter='計數器';
$jnstr_check_setted='有設定';
$jnstr_check_notset='沒有設定';
$jnstr_check_lock='鎖定';
$jnstr_check_mode='形式';
$jnstr_check_dir='目錄';
$jnstr_check_img='畫像';
$jnstr_sampleresize='縮圖產生';
$jnstr_have='有';
$jnstr_nothave='無';
$jnstr_chibi_gotobbs="到留言板";
$jnstr_chibi_showpost_pre="留言板的首";
$jnstr_chibi_showpost_post=$jnstr_post_n."的記事以順序顯示。";

$jnstr_chibi_rights_1=<<"EOM";
    <a href="http://www.kent-web.com/" target="_blank">KENT</a> &amp; <a href="http://village.infoweb.ne.jp/~fwhf2602/" target="_blank">MakiMaki</a>
    <p style="color: #585eaa;"><strong>KENT</strong>さんの掲示板「<strong>YY-BOARD</strong>」を ・・・・・</p>
EOM

$jnstr_chibi_rights_2=<<"EOM";
    <a href="http://homepage2.nifty.com/nejifactory/" target="_blank">NejiFactory</a>
    <p style="color: #005344;"><strong>NejiFactory</strong>さんの「<strong>ちびぼーど</strong>」風に表示する為の ・・・・・</p>
EOM

$jnstr_chibi_rights_3=<<"EOM";
    コード参考<a href="http://yurii.oheya.to/" target="_blank">*繊細友の会ｌａｂ*</a>
    <p style="color: #aa363d;">閲覧専用のＣＧＩなのです！！ ＼(-o-;)／</p>
EOM

$jnstr_chibi_notice=<<"EOM";
    注意 )
    <p style="color: #472d56;">此CGI的閲覧以外的機能都依存於「Joyful Note」。</p>
EOM

$jnstr_modcap_publish='發行Cap';
$jnstr_modcap_del='抹消Cap';
$jnstr_modcap_showall='Cap一覧';
$jnstr_modcap_stop_hint='(停止＝請選擇想抹消的Cap然後按[停止]。)';
$jnstr_modcap_stop='停止Cap';
$jnstr_modcap_nocap='沒有這個Cap喲！';
$jnstr_modcap_ereased_title='Cap已經抹消';
$jnstr_modcap_ereased_header='Cap抹消成功';
$jnstr_modcap_ereased_body='已經抹消。';
$jnstr_modcap_erease_title='Cap抹消表單';
$jnstr_modcap_erease_hint='[停止發行的Cap的名稱]';
$jnstr_modcap_publish_ngchar='名稱中含有不能用的字元。';
$jnstr_modcap_publish_starchar='名稱中不能含有★。';
$jnstr_modcap_publish_longname='名稱太長。';
$jnstr_modcap_publish_longpass='Cap密碼太長。';
$jnstr_modcap_publish_samecap='已經有相同的Cap。';
$jnstr_modcap_publish_finish_title='Cap發行成功';
$jnstr_modcap_publish_finish_header='Cap發行成功！';
$jnstr_modcap_publish_finish_body='Cap已經發行。';
$jnstr_modcap_namecolor='名前的顏色';
$jnstr_modcap_capsuffix='Cap接尾語';
$jnstr_modcap_publish_form='Cap發行表單';
$jnstr_modcap_publish_cappass='Cap密碼';
$jnstr_modcap_publish_hint='(最後的★不需要輸入。投稿時會自動顯示。)';
$jnstr_res_mode='回應模式';
$jnstr_edit_mode='修正模式';
