# makefile for SCO OpenServer
#
# Copyright (c) 2006 Ken Kato

AS = as
ASFLAGS =

CC = gcc
CFLAGS = -O

LD = $(CC)
LDFLAGS =

VMCALL_O = vmcall.sco.o

CPPFLAGS = -DHAVE_STDINT_H -DHAVE_SETTIMEOFDAY -DHAVE_SIGLONGJMP -DHAVE_USLEEP

VMWLIB =
SHRLIB =
FTPLIB =

include Makefile.inc
