# makefile for OpenBSD
#
# Copyright (c) 2006 Ken Kato

AS = as
ASFLAGS =

CC = gcc
CFLAGS = -O2

LD = gcc
LDFLAGS =

# replace the following line if you prefer inline version
# of vmcall functions (vmcall.c) -- works only with gcc
# VMCALL_O = vmcall.o
VMCALL_O = vmcall.gas.o

CPPFLAGS = -DHAVE_INTTYPES_H -DHAVE_CLOCK_SETTIME -DHAVE_SIGLONGJMP -DHAVE_NANOSLEEP

VMWLIB =
SHRLIB =
FTPLIB =

include Makefile.inc
