# makefile for Linux
#
# Copyright (c) 2006 Ken Kato

AS = as
ASFLAGS =

CC = gcc
CFLAGS = -O2

LD = gcc
LDFLAGS =

# replace the following line if you prefer inline version
# of vmcall functions (vmcall.c)
# VMCALL_O = vmcall.o
VMCALL_O = vmcall.gas.o

CPPFLAGS = -DHAVE_STDINT_H -DHAVE_CLOCK_SETTIME -DHAVE_SIGLONGJMP -DHAVE_NANOSLEEP -DHAVE_ICONV_H

VMWLIB = -lrt
SHRLIB =
FTPLIB =

include Makefile.inc
