//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PokemonMemHack.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_POKEMONMEMHACK_DIALOG       102
#define IDS_ERR_STRING_READ             102
#define IDS_ERR_MEM_ACCESS              103
#define IDS_ERR_INIT                    104
#define IDD_MEM_PM                      129
#define IDD_MEM_PM_BASIC                130
#define IDD_MEM_PM_ABILITY              131
#define IDD_MEM_PM_SKILL                132
#define IDD_MEM_PM_RIBBON               134
#define IDD_MEM_PM_MISC                 135
#define IDD_MEM_MISC0                   138
#define IDD_MEM_MISC1                   139
#define IDD_MEM_MISC2                   140
#define IDR_MAINFRAME                   142
#define IDC_REFRESH                     1000
#define IDC_CONFIRM                     1001
#define IDC_TAB                         1005
#define IDC_PM_LIST                     1010
#define IDC_NICK_NAME                   1020
#define IDC_CATCHER_NAME                1021
#define IDC_BREED_LIST                  1030
#define IDC_CHAR                        1040
#define IDC_ID                          1041
#define IDC_CHAR_TITLE                  1045
#define IDC_ID_TITLE                    1046
#define IDC_ITEM_LIST                   1050
#define IDC_ITEM_DESC                   1051
#define IDC_PS_LIST                     1060
#define IDC_PS_DESC                     1061
#define IDC_LEVEL_LIST                  1063
#define IDC_SPEC_LIST                   1070
#define IDC_SPEC_DESC                   1071
#define IDC_INTIMATE                    1080
#define IDC_SEX_LIST                    1081
#define IDC_EXP                         1090
#define IDC_INDV_HP                     1100
#define IDC_INDV_ATK                    1101
#define IDC_INDV_DEF                    1102
#define IDC_INDV_DEX                    1103
#define IDC_INDV_SATK                   1104
#define IDC_INDV_SDEF                   1105
#define IDC_INDV_MAX                    1110
#define IDC_BB_HP                       1120
#define IDC_BB_ATK                      1121
#define IDC_BB_DEF                      1122
#define IDC_BB_DEX                      1123
#define IDC_BB_SATK                     1124
#define IDC_BB_SDEF                     1125
#define IDC_BB_MAX                      1130
#define IDC_BB_SUM                      1131
#define IDC_AP_COOL                     1140
#define IDC_AP_BEAUTIFUL                1141
#define IDC_AP_CUTE                     1142
#define IDC_AP_WISE                     1143
#define IDC_AP_TOUGH                    1144
#define IDC_AP_WEAK                     1145
#define IDC_AP_MAX                      1150
#define IDC_MEM_SKILL0                  1160
#define IDC_MEM_SKILL1                  1161
#define IDC_MEM_SKILL2                  1162
#define IDC_MEM_SKILL3                  1163
#define IDC_MEM_SKILL_NAME0             1165
#define IDC_MEM_SKILL_NAME1             1166
#define IDC_MEM_SKILL_NAME2             1167
#define IDC_MEM_SKILL_NAME3             1168
#define IDC_MEM_PP0                     1170
#define IDC_MEM_PP1                     1171
#define IDC_MEM_PP2                     1172
#define IDC_MEM_PP3                     1173
#define IDC_MEM_PP_MAX                  1174
#define IDC_MEM_PP_BOOST0               1180
#define IDC_MEM_PP_BOOST1               1181
#define IDC_MEM_PP_BOOST2               1182
#define IDC_MEM_PP_BOOST3               1183
#define IDC_MEM_PP_BOOST_ALL            1184
#define IDC_SKILL_DESC                  1185
#define IDC_LEGAL_SKILL_LIST            1186
#define IDC_POKEBALL_LIST               1190
#define IDC_POKERUS                     1191
#define IDC_BLACK_POINT                 1192
#define IDC_STATUS_LIST                 1193
#define IDC_AREA_LIST                   1200
#define IDC_INIT_LEVEL                  1201
#define IDC_GAME_VERSION_LIST           1202
#define IDC_MARK0                       1220
#define IDC_MARK1                       1221
#define IDC_MARK2                       1222
#define IDC_MARK3                       1223
#define IDB_MARK0                       1230
#define IDB_MARK1                       1231
#define IDB_MARK2                       1232
#define IDB_MARK3                       1233
#define IDC_SHINY                       1240
#define IDC_EGG                         1250
#define IDC_OBEDIENCE                   1251
#define IDC_CUR_LEVEL                   1260
#define IDC_CUR_HP_CUR                  1261
#define IDC_CUR_HP_CAP                  1262
#define IDC_CUR_ATK                     1263
#define IDC_CUR_DEF                     1264
#define IDC_CUR_DEX                     1265
#define IDC_CUR_SATK                    1266
#define IDC_CUR_SDEF                    1267
#define IDC_AUTO_CALC                   1270
#define IDC_ST_SLEEP                    1280
#define IDC_ST_POISON                   1281
#define IDC_ST_BURN                     1282
#define IDC_ST_FREEZE                   1283
#define IDC_ST_PARALYZE                 1284
#define IDC_ST_STRONG_POISON            1285
#define IDC_COOL0                       1290
#define IDC_COOL1                       1291
#define IDC_COOL2                       1292
#define IDC_COOL3                       1293
#define IDC_COOL4                       1294
#define IDC_BEAUTIFUL0                  1300
#define IDC_BEAUTIFUL1                  1301
#define IDC_BEAUTIFUL2                  1302
#define IDC_BEAUTIFUL3                  1303
#define IDC_BEAUTIFUL4                  1304
#define IDC_CUTE0                       1310
#define IDC_CUTE1                       1311
#define IDC_CUTE2                       1312
#define IDC_CUTE3                       1313
#define IDC_CUTE4                       1314
#define IDC_WISE0                       1320
#define IDC_WISE1                       1321
#define IDC_WISE2                       1322
#define IDC_WISE3                       1323
#define IDC_WISE4                       1324
#define IDC_TOUGH0                      1330
#define IDC_TOUGH1                      1331
#define IDC_TOUGH2                      1332
#define IDC_TOUGH3                      1333
#define IDC_TOUGH4                      1334
#define IDC_DEFEAT_CHAMPION             1340
#define IDC_BATTLE_TOWER_50             1341
#define IDC_BATTLE_TOWER_OPEN           1342
#define IDC_ART_MODEL                   1343
#define IDC_FULL_BB                     1344
#define IDC_UNK_RIBBON0                 1345
#define IDC_UNK_RIBBON1                 1346
#define IDC_UNK_RIBBON2                 1347
#define IDC_UNK_RIBBON3                 1348
#define IDC_UNK_RIBBON4                 1349
#define IDC_UNK_RIBBON5                 1350
#define IDC_UNK_RIBBON6                 1351
#define IDC_RIBBONS_25                  1360
#define IDC_RIBBONS_32                  1361
#define IDC_RIBBONS_0                   1362
#define IDC_PLAYER_NAME                 1400
#define IDC_PLAYER_ID                   1401
#define IDC_MONEY                       1402
#define IDC_COIN                        1403
#define IDC_DUST                        1404
#define IDC_SPRAY_TIME                  1410
#define IDC_SAFARI_TIME                 1411
#define IDC_BP_CURRENT                  1412
#define IDC_BP_TRAINERCARD              1413
#define IDC_UPGRADE_POKEDEX             1420
#define IDC_FULL_POKEDEX                1421
#define IDC_MAX_INTI                    1430
#define IDC_MAX_INDV                    1431
#define IDC_MAX_BB                      1432
#define IDC_MAX_AP                      1433
#define IDC_RAND_ID                     1434
#define IDC_GIVE_ALL_POKEMON            1440
#define IDC_SET_POKEBALL                1441
#define IDC_SET_INDV                    1442
#define IDC_SET_OBEDIENCE               1443
#define IDC_MISC_ITEM_LIST              1450
#define IDC_MISC_ITEM_QUANTITY          1451
#define IDC_MISC_ITEM_DESC              1452
#define IDC_ADD_ITEM                    1460
#define IDC_ADD_ITEM_BP50               1461
#define IDC_ADD_ITEM_BP60               1462
#define IDC_MAX_VIEW_IN_BP              1463
#define IDC_INC_ITEMS                   1470
#define IDC_GIVE_POKEBALLS              1471
#define IDC_GIVE_MACHINES               1472
#define IDC_GIVE_BERRIES                1473
#define IDC_GIVE_POKEBLOCKS             1474
#define IDC_GIVE_DECORATES              1475
#define IDC_DROP_LAST_KEYITEM           1476
#define IDC_ENABLE_ALL_TICKETS          1477
#define IDC_GIVE_BADGES                 1480
#define IDC_ENABLE_MIRAGE_ISLAND        1481
#define IDC_ADJUST_CLOCK                1482
#define IDC_LOCK_STEP_COUNTER_TO_FE     1490
#define IDC_LOCK_DAYCARE_COUNTER2_TO_FE 1491
#define IDC_LOCK_EXP_GAIN_TO_7FFF       1492
#define IDC_PC_SEX_RANDOM               1500
#define IDC_PC_SEX_FEMALE               1501
#define IDC_PC_SEX_MALE                 1502
#define IDC_PC_LEVEL                    1505
#define IDC_BREED_HP                    1510
#define IDC_BREED_ATK                   1511
#define IDC_BREED_DEF                   1512
#define IDC_BREED_DEX                   1513
#define IDC_BREED_SATK                  1514
#define IDC_BREED_SDEF                  1515
#define IDC_BREED_ABL_SUM               1516
#define IDC_NO_NAME                     1900
#define IDC_ENABLE_TEXT                 1901
#define IDC_SECRET                      2490
#define IDC_DECODE                      2491
#define IDC_ENCODE                      2492
#define IDC_RESET                       2493
#define IDC_ADDRESS                     2494
#define IDC_LANG_CN                     2500
#define IDC_LANG_JP                     2501
#define IDC_LANG_EN                     2502
#define IDC_COUNT_NONE                  2510
#define IDC_COUNT_DEC                   2511
#define IDC_COUNT_HEX                   2512
#define IDC_PC_NAME_JP                  2520
#define IDC_PC_NAME_EN                  2521
#define IDC_PC_NAME_NUMBER              2522
#define IDC_MOVE_UP                     2530
#define IDC_MOVE_DOWN                   2531

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1911
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
